### ISSUE TITLE
apt17scan & hikitconfig errors: "too many values to unpack"

### ISSUE THREAD

**Issue by jared703** [JPCERTCC/aa-tools#1]
Team,

I'm getting an error with both apt17scan and hikitconfig with both 2.4 and 2.5 versions of Volatility. Please let me know if I can provide more detail/testing.

Full error:

Traceback (most recent call last):
  File "/vol-2.5_clean/vol.py", line 192, in <module>
    main()
  File "/vol-2.5_clean/vol.py", line 183, in main
    command.execute()
  File "/vol-2.5_clean/volatility/commands.py", line 145, in execute
    func(outfd, data)
  File "/vol-2.5_clean/volatility/plugins/apt17scan.py", line 156, in render_text
    for task, start, malname in data:
ValueError: too many values to unpack

**Comment by shu-tom** [comment]
@jared703 thank you for reporting the issues.
I've fixed the bug. e3e1d9e48aebf3808d7e89a92775d8d3b3137e89

**Comment by jared703** [comment]
I confirmed this is working. Keep up the good work!
